account/urls.py
from os import terminal_size
from django.urls import path, re_path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import *

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.account, name='account'),
    path('login/', views.login, name='login'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_confirm, name="password_reset_confirm"),
    path('user/<str:username>/', views.user_profile, name='user_profile'),
    path('user/<str:username>/<str:inf>/', views.account_animes, name='account_animes'),
    path('logout/', views.logout, name='logout'),
    path('animes-favorite/<str:name>/', views.animes_favorites_check, name='animes-favorite_check'),
    path('animes-favorite/', views.animes_favorites, name='animes-favorite'),
    path('تم-مشاهدتها/<str:name>/', views.done_show_check, name='done_show_add'),
    path('تم-مشاهدتها/', views.done_show_views, name='done_show'),
    path('أرغب-بمشاهدتها/<str:name>/', views.want_show_check, name='want_show_add'),
    path('أرغب-بمشاهدتها/', views.want_show_views, name='want_show'),
    path('activate-user/<uidb64>/<token>/', views.activate, name='activate'),
]

animes/urls.py
from django.conf.urls import handler404, url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', include('pages.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('anime/', include('urlanime.urls')),
    
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'urlanime.views.error404'
handler403 = 'urlanime.views.error403'
handler500 = 'urlanime.views.error500'

pages/urls.py
from django.urls import path, re_path
from . import views
from django.views.static import serve 
from django.conf.urls.static import static
from django.conf import settings
from account.views import login 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('', views.index, name='index'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('admin/login/', views.page_reset, name='admin-login'),
    path('قائمة-الأنمي/', views.list_anime, name='list_anime'),
    path('categorie/<str:name>/<str:slug>/', views.ht, name='ht'),
    path('episode/', views.episode, name='episode'),
    path('search/', views.search, name='search'),
    path('مواعيد-عرض-حلقات-الانمي/', views.days_anime, name='days_anime')
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from pages.models import *
import uuid
from django.utils import timezone
from PIL import Image
from  django.conf import settings
import os
# Create your models here.
class UsersBack(models.Model):
    choices = (
        ('prive', 'prive'),
        ('public', 'public')
    )

    user = models.OneToOneField(User,  related_name='user',on_delete=models.CASCADE)

    bio = models.TextField(blank=True, null=True)

    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")

    animes_fav = models.ManyToManyField(Anime, related_name='fav', blank=True)

    animes_done = models.ManyToManyField(Anime, related_name='done', blank=True) 

    animes_want = models.ManyToManyField(Anime, related_name='want', blank=True) 

    following = models.ManyToManyField(User, related_name='following',blank=True) 

    social_twitter = models.CharField(max_length=200, blank=True, null=True)

    social_instagram = models.CharField(max_length=200, blank=True, null=True)

    social_github = models.CharField(max_length=200, blank=True, null=True)

    social_website = models.URLField(max_length=200, blank=True, null=True)
    
    created = models.DateTimeField(default=timezone.now)

    information_public = models.BooleanField(default=True)

    notification = models.BooleanField(default=True)

    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def save(self):
        super().save()
        if self.profile_image.width > 300 and self.profile_image.height > 300:
            size = (300, 300)
            img = Image.open(self.profile_image.path)
            img.thumbnail(size)
            img.save(self.profile_image.path)


    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url

class Tokens(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=200)
    work = models.CharField(max_length=200)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.token

class Domain(models.Model):
    domain = models.CharField(max_length=400)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
class RegisterForm(forms.ModelForm):
    username = forms.CharField(label="اسم المستخدم ", max_length=30, help_text="اسم المستخدم يجب ألا يحتوي على مسافات")
    email = forms.EmailField(label="البريد الالكتروني ")
    password1 = forms.CharField(label="كلمة المرور ", widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(label="تأكيد كلمة المرور ", widget=forms.PasswordInput(), min_length=8)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(forms.ModelForm):
    username = forms.CharField(label="اسم المستخدم ", max_length=30)
    password = forms.CharField(label="كلمة المرور ", widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'password')



    

account/views.py
from django.conf.urls import url
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from django.contrib.admin.models import *
from django.contrib import auth
from pages.models import *
from django.http import JsonResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import *
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import  force_bytes, force_str, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
import re
from django.conf import settings
from .utils import generate_token
from django.contrib import admin
from animes import urls
from django.urls import path, include
from django.http import *
import secrets
import time
# Create your views here.

def ajax(request):
    
    #return render(request, 'pages/error500.html')
    return JsonResponse({'user': 'hamza'})

def send_message(user,request):
    domain = get_current_site(request)
    subject = 'Activate Your Account'
    token = secrets.token_hex(14).title()
    tk = Tokens(user=user, token=token, work='activate_account').save()
    context = {
        'user':user,
        'domain': domain,
        'uid': urlsafe_base64_encode(force_bytes(user.email)),
        'token': token,
    }

    body = render_to_string('account/activate.html', context)

    # Please use the link below to verify your account.

    # https://{domain}/account/activate-user/{context["uid"]}/{context["token"]}'''

    try:
        send_mail(
            subject,
            body,
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False
        )
    except:
        return 'not'
    #return render(request, 'pages/index.html')

def user_profile(request, username):
    domain = get_current_site(request)
    try:
        user = User.objects.get(username=username)
    except:
        raise Http404
    try:
        user_back = UsersBack.objects.get(user=user, information_public=True)
    except:
        raise Http404
    x = {
        'user': user_back,
        'domain': domain,
        'title_tag': username
    }

    return render(request, 'users/user-profile.html', x)

def account_animes(request, username, inf):
    domain = get_current_site(request)
    try:
        user = User.objects.get(username=username)
    except:
        raise Http404
    try:
        user_back = UsersBack.objects.get(user=user, information_public=True)
    except:
        raise Http404

    if inf == 'الأنميات-المفضلة' :
        paginator = Paginator(user_back.animes_fav.all(), 24)
        title = 'الأنميات المفضلة'

    elif inf == 'تم-مشاهدتها':
        paginator = Paginator(user_back.animes_done.all(), 24)
        title = 'أنميات تم مشاهدتها'

    elif inf == 'أرغب-بمشاهدتها':
        paginator = Paginator(user_back.animes_want.all(), 24)
        title = 'أنميات أرغب بمشاهدتها'

    else:
        raise Http404

    s = 1
    title = 'الأنميات المفضلة'
    anime_type = AnimeType.objects.all()
    anime_state = AnimeState.objects.all()
    anime_date = AnimeDate.objects.all()
    anime_class = AnimeClass.objects.all()

    if request.method == 'GET':
            if 'page' in request.GET:
                s = request.GET['page']

    

    try:
        page = paginator.page(s)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    if page.number <= 1:
        page.range = range(page.number, paginator.num_pages+1)[:3]
    elif page.number == 2:
        page.range = range(page.number-1, paginator.num_pages+1)[:4]
    else:
        page.range = range(page.number-2, paginator.num_pages+1)[:5]


    
    for anime in page:
        anime.url_anime = urlsafe_base64_encode(force_bytes(anime.name))
        anime.title = anime.name.title()

    for i in anime_class:
        i.url_anime = i.name.replace(' ', '-')

    for i in anime_state:
        i.url_anime = i.name.replace(' ', '-')

    for i in anime_type:
        i.url_anime = i.name.replace(' ', '-')
    
    x = {
        'title': title,
        'page': page,
        'anime_type': anime_type,
        'anime_state': anime_state,
        'anime_date': anime_date,
        'anime_class': anime_class,
        'domain': domain,
        'title_tag': username
    }
    return render(request, 'pages/list-anime.html', x)


def reset_password(request):
    if request.user.is_authenticated:
        return redirect('index')
    messages = []
    error = None
    domain = get_current_site(request)
    if request.method == 'POST':
        if not ('email' in request.POST):
            error = 'بريدك الإلكتروني فارغ'
        else:
            email = request.POST['email']
            user = None
            try:
                user = User.objects.get(email=email)
            except:
                error = 'بريدك الإلكتروني غير صحيح'
            try:
                user = UsersBack.objects.get(user=user, is_active=True)
                user = user.user
            except:
                error = 'بريدك الإلكتروني غير مفعل'
                user = None 
            if user:
                
                try:
                    tk = Tokens.objects.get(user=user, work='reset_password').delete()
                except:
                    pass
                token = secrets.token_hex(14).title()
                token_db = Tokens(user=user, token=token, work='reset_password').save()
               
                subject = 'reset password'
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                
                body = f'''
                You're receiving this email because you requested a password reset for your user account at {domain}.

                Please use the link below to reset your Password

                http://{domain}/account/reset-password/{uid}/{token}/

                Your username, in case you’ve forgotten: {user.username}
                
                '''
               

                try:
                    send_mail(
                        subject,
                        body,
                        settings.EMAIL_HOST_USER,
                        [user.email],
                        fail_silently=False
                    )
                    messages.append('المرجو التحقق من بريدك الالكتروني')
                except:
                    error = 'خطأ'

    x = {
        'page': 'reset_password',
        'error': error,
        'title': 'تغيير كلمة السر',
        'messages': messages,
        'domain': domain
    }
    return render(request, 'account/login.html', x)

def reset_password_confirm(request, uidb64, token):
    if request.user.is_authenticated:
        raise Http404
    
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        
    except Exception as e :
        user=None
    
    try:
        tk = Tokens.objects.get(user=user, work='reset_password')
        
    except Exception as e :
        tk=None

    messages = []
    error = None
    if user and tk :
        if request.POST:
            if not('password1' in request.POST):
                error = 'الحقل الأول فارغ'
            elif not('password2' in request.POST):
                error = 'الحقل الثاني فارغ'
            else:
                password1 = request.POST['password1']
                password2 = request.POST['password2']

                if password1 != password2:
                    error = 'كلمة المرور غير متطابقة'
                elif password1.find(' ') != -1:
                    error = 'كلمة المرور يجب ألا يحتوي على مسافات'
                elif len(password1) <= 8:
                     error = 'كلمة المرور يجب أن تكون أكثر من 8 حروف'
                elif password1.isdigit():
                    error = 'كلمة المرور لا يجب أن تحتوي على أرقام فقط'
                else:
                    user.set_password(password1)
                    user.save()
                    k = tk.delete()

                    auth.login(request, user)
                    return redirect('index')
        x = {
            'title': 'تغيير كلمة السر',
            'title_tag': 'تغيير كلمة السر',
            'error': error,
            'domain': get_current_site(request),
        }
        return render(request, 'account/reset.html', x) 
    raise Http404


def register(request):
    if not request.user.is_authenticated:

        val_email = ''
        val_user = ''
        val_pass1 = ''
        val_pass2 = ''
        error = None
        if request.method == "POST":
            username = ''
            email = ''
            password1 = ''
            password2 = ''
            terms = ''
            if 'username' in request.POST:
                username = request.POST['username']

            if 'email' in request.POST:
                email = request.POST['email']

            if 'password1' in request.POST:
                password1 = request.POST['password1']

            if 'password2' in request.POST:
                password2 = request.POST['password2']
            if 'terms' in request.POST:
                terms = request.POST['terms']

            
            val_pass1 = password1
            val_pass2 = password2
            val_user = username
            val_email = email

            if terms != 'on':
                error = 'أنت غير موافق على الشروط'
            elif not (username and email and password1 and password2) :
                error = 'حقل فارغ'
            elif username.find(' ') != -1:
                error = 'سم المستخدم يجب ألا يحتوي على مسافات'
            elif User.objects.filter(username=username).exists():
                    error = 'اسم المستخدم موجود مسبقاً'
            elif User.objects.filter(email=email).exists():

templates/users/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <link rel="stylesheet" href="{% static 'css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="hamza-animes, hamza-animes.herokuapp,AnimeLek,Anime 2020, Anime4up, Okanime,انمي,انمي ليك الجديد,انمي ليك,Anime Lek,الانمي,مشاهدة,تحميل,مسلسلات,افلام,افلام انمي,New AnimeLek,Okanime,Animelek,Ahiru no Sora مترجم,Nanatsu No Taizai,Boku no Hero Academia,Haikyuu!!,جميع المواسم أنمي هايكيوا,أنمي One Piece/ون بيس مترجم,جميع المواسم أنمي  Shokugeki no Souma مترجم,انمي Dragon Ball Super/دراغون بول سوبر مترجم,BLACK CLOVER مترجم,جميع المواسم  الانمي بوكيمون Pokemon مترجم,جميع مواسم الانميKingdom مترجم,انمي Kaguya-sama wa Kokurasetai مترجم,انمي Vinland Saga مترجم,مترجمة اون لاين وتحميل" />
    <title>سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين </title>
    <meta name="description" content="يمكنكم مشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين " />
    <meta itemprop="name" content="سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <meta property="og:title" content="سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <meta property="og:url" content="https://{{domain}}{{request.path}}">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <meta name="twitter:description" content="يمكنكم مشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@600&display=swap');
    </style>
</head>
<body>

<!-- Main Section -->
<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href=""><i class="im im-edit"></i>
              Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{profile.imageURL}}" />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_into}}</p>
            <p class="dev__location">Based in {{profile.location}}</p>

            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
              </li>
              {% endif %}


              {% if profile.social_twitter %}
              <li>
                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
              </li>
              {% endif %}

              {% if profile.social_linkedin %}
              <li>
                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i
                    class="im im-linkedin"></i></a>
              </li>
              {% endif %}

              {% if profile.social_website %}
              <li>
                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                    class="im im-globe"></i></a>
              </li>
              {% endif %}

            </ul>


          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{profile.bio}}</p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href=""><i
              class="im im-plus"></i> Add Skill</a>
        </div>

        <table class="settings__table">
          {% for skill in skills %}
          <tr>
            <td class="settings__tableInfo">
              <h4>{{skill.name}}</h4>
              <p>
                {{skill.description}}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href=""><i
                  class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="?next=/account"><i
                  class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href=""><i
              class="im im-plus"></i> Add Project</a>
        </div>

        <table class="settings__table">
          {% for project in projects %}
          <tr>
            <td class="settings__thumbnail">
              <a href=""><img src="{{project.imageURL}}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="">{{project.title}}</a>
              <p>{{project.description|slice:"150"}}</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href=""><i
                  class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn"
                href="?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}

        </table>
      </div>
    </div>
  </div>
</main>

</body>
</html>

templates/users/edit-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <link rel="stylesheet" href="{% static 'css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="hamza-animes, hamza-animes.herokuapp,AnimeLek,Anime 2020, Anime4up, Okanime,انمي,انمي ليك الجديد,انمي ليك,Anime Lek,الانمي,مشاهدة,تحميل,مسلسلات,افلام,افلام انمي,New AnimeLek,Okanime,Animelek,Ahiru no Sora مترجم,Nanatsu No Taizai,Boku no Hero Academia,Haikyuu!!,جميع المواسم أنمي هايكيوا,أنمي One Piece/ون بيس مترجم,جميع المواسم أنمي  Shokugeki no Souma مترجم,انمي Dragon Ball Super/دراغون بول سوبر مترجم,BLACK CLOVER مترجم,جميع المواسم  الانمي بوكيمون Pokemon مترجم,جميع مواسم الانميKingdom مترجم,انمي Kaguya-sama wa Kokurasetai مترجم,انمي Vinland Saga مترجم,مترجمة اون لاين وتحميل" />
    <title>سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين </title>
    <meta name="description" content="يمكنكم مشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين " />
    <meta itemprop="name" content="سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <meta property="og:title" content="سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <meta property="og:url" content="https://{{domain}}{{request.path}}">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="سجل دخولك لمشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <meta name="twitter:description" content="يمكنكم مشاهدة احدث حلقات و أفلام الانمي مترجمة اون لاين ">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@600&display=swap');
    </style>
</head>
<body>
{% load crispy_forms_tags %}
    
    
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="/account/"><i class="im im-angle-left"></i></a>
            <br>
            {% if error != '' %}
                <div class="form__field">
                    <p style='color: red;direction: rtl;font-family: Cairo, sans-serif;' class='messages'>{{error}}</label>
                </div>
            {% endif %}
            <form class="form" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__field" style="direction:rtl;">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">اسم المستخدم</label>
                    <input type="text" style="direction:rtl;" name="username" value="{{value_username}}" maxlength="200" class="input" id="id_username">
                    <p style='color:gray; font-size: 13px;font-family: Cairo, sans-serif;margin-top:3px;'>اسم المستخدم يجب ألا يحتوي على مسافات</p>
                </div>
                
                <div class="form__field">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">معلومات عنك</label>
                    <textarea name="bio" style="direction:rtl;" cols="40" rows="10" class="input" id="id_bio">{{value_bio}}</textarea>
                </div>
                
                
                <div class="form__field">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">صورة الغلاف</label>
                    Currently: <a href="{{profile_image.url}}">{{profile_image.url}}</a>
                Change:
                <input  type="file" name="profile_image" accept="image/*" class="input" id="id_profile_image">
                    </div>
                
                <div class="form__field">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">حساب github الخاص بك</label>
                    <input type="text" name="social_github" value="{{value_github}}" maxlength="200" class="input" id="id_social_github">
                </div>
                
                <div class="form__field">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">حساب instagram الخاص بك</label>
                    <input type="text" name="social_instagram" value="{{value_instagram}}" maxlength="200" class="input" id="id_social_linkedin">
                </div>
                
                <div class="form__field">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">حساب twitter الخاص بك</label>
                    <input type="text" name="social_twitter" value="{{value_twitter}}" maxlength="200" class="input" id="id_social_twitter">
                </div>
                
                <div class="form__field">
                    <label for="formInput#text" style="direction:rtl;font-family: Cairo, sans-serif;">موقعك</label>
                    <input type="text" name="social_website" value="{{value_website}}" maxlength="200" class="input" id="id_social_website">
                </div>

                 <div class="form-group" style="direction:rtl;height:30px">
                    <label  style='font-family: Cairo, sans-serif;' for="notification">الإشعارات</label><input  type="checkbox" style="margin-right:15px;" name="notification" id="notification" class='input' {{notification}}>
                    
                </div>

                <div class="form-group"  style="direction:rtl;height:30px">
                    <label  style='font-family: Cairo, sans-serif;' for="public"> رؤية الأخرين للملف الشخصي الخاص بك (Profile) </label><input  type="checkbox" style="margin-right:15px;" name="public" id="public" class='input' {{public}}>
                    
                </div>
                

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="save" />
            </form>
        </div>
    </div>
</main>

    

</body>
</html>
    

templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>

    <ul class="messages">
      {% for message in messageRequests %}
      {% if message.is_read == False %}
      <li class="message message--unread">
        {% else %}
      <li class="message">
        {% endif %}

        <a href="{% url 'message' message.id %}">
          <span class="message__author">{{message.name}}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</main>

{% endblock content %}

templates/users/message.html
{% extends 'main.html' %}


{% block content %}
<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
      <h2 class="message__subject">{{message.subject}}</h4>
        {% if message.sender %}
        <a href="{% url 'user-profile' message.sender.id  %}" class="message__author">{{message.name}}</a>
        {% else %}
        <p class="message__author">{{message.name}}</p>
        {% endif %}
        <p class="message__date">{{message.created}}</p>
        <div class="message__body">{{message.body|linebreaksbr}}</div>
    </div>
  </div>
</main>
{% endblock content %}

templates/users/skill_form.html
{% extends 'main.html' %}

{% block content %}


<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" action="">
                {% csrf_token %}

                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text"> {{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>



{% endblock %}